const $ = id => document.getElementById(id);
const fmtINR = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n);

function calcAge(){const v=$('dob').value;if(!v)return $('ageResult').textContent='Please select a date.';const b=new Date(v),t=new Date();if(b>t)return $('ageResult').textContent='Date of birth cannot be in the future.';let y=t.getFullYear()-b.getFullYear(),m=t.getMonth()-b.getMonth(),d=t.getDate()-b.getDate();if(d<0){m--;d+=new Date(t.getFullYear(),t.getMonth(),0).getDate()}if(m<0){y--;m+=12}$('ageResult').textContent=`${y} years, ${m} months, ${d} days`;}
function calcEMI(){const P=+$('loan').value,R=+$('rate').value/1200,N=+$('months').value;if(!(P>0&&N>0)||R<0)return $('emiResult').textContent='Enter valid values.';const emi=R===0?P/N:P*R*Math.pow(1+R,N)/(Math.pow(1+R,N)-1);$('emiResult').textContent=`Monthly EMI: ${fmtINR(emi)} • Total: ${fmtINR(emi*N)}`;}
function calcGST(){const a=+$('gstAmount').value,r=+$('gstRate').value/100,mode=$('gstMode').value;if(!(a>=0))return $('gstResult').textContent='Enter a valid amount.';if(mode==='add'){const tax=a*r;$('gstResult').textContent=`GST: ${fmtINR(tax)} • Total: ${fmtINR(a+tax)}`}else{const base=a/(1+r),tax=a-base;$('gstResult').textContent=`Base: ${fmtINR(base)} • GST: ${fmtINR(tax)}`}}
function calcPercent(){const p=+$('pct').value,n=+$('pctNum').value;if(Number.isNaN(p)||Number.isNaN(n))return $('pctResult').textContent='Enter valid values.';$('pctResult').textContent=`${p}% of ${n} = ${(p*n/100).toLocaleString('en-IN')}`;}
$('wordText')?.addEventListener('input',e=>{const s=e.target.value.trim(),w=s?s.split(/\s+/).length:0;$('wordResult').textContent=`${w} words • ${e.target.value.length} characters`;});
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image(),u=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=reject;img.src=u;});}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);}
async function compressImage(){const f=$('compressInput').files[0];if(!f)return $('compressResult').textContent='Choose an image first.';const img=await loadImage(f),c=$('workCanvas'),ctx=c.getContext('2d');c.width=img.width;c.height=img.height;ctx.drawImage(img,0,0);c.toBlob(blob=>{if(!blob)return;downloadBlob(blob,'toolbhai-compressed.jpg');const save=Math.max(0,100-(blob.size/f.size*100));$('compressResult').textContent=`Done: ${(blob.size/1024).toFixed(1)} KB • ~${save.toFixed(0)}% smaller`;},'image/jpeg',+$('quality').value);}
async function resizeImage(){const f=$('resizeInput').files[0],w=+$('resizeW').value,h=+$('resizeH').value;if(!f||!(w>0&&h>0))return $('resizeResult').textContent='Choose an image and enter width + height.';const img=await loadImage(f),c=$('workCanvas'),ctx=c.getContext('2d');c.width=w;c.height=h;ctx.clearRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);c.toBlob(blob=>{downloadBlob(blob,'toolbhai-resized.png');$('resizeResult').textContent=`Done: ${w}×${h}px`},'image/png');}
function makeQR(){const t=$('qrText').value.trim();if(!t)return $('qrWrap').textContent='Enter text or a link.';const url='https://quickchart.io/qr?size=220&text='+encodeURIComponent(t);$('qrWrap').innerHTML=`<img alt="Generated QR code" src="${url}">`;}
function makePrompt(){const task=$('promptTask').value.trim(),tone=$('promptTone').value;if(!task)return $('promptResult').textContent='Enter your task first.';$('promptResult').textContent=`Act as an expert assistant. Your task: ${task}. Use a ${tone.toLowerCase()} tone. Give a clear, accurate answer with practical steps and examples where useful.`;}
function makeTitles(){const t=$('ytTopic').value.trim();if(!t)return $('ytResult').textContent='Enter a video topic first.';const arr=[`${t}: Complete Beginner Guide`,`7 Things You Must Know About ${t}`,`I Tried ${t} — Here’s What Happened`,`${t} Explained Simply`,`Stop Making These ${t} Mistakes`];$('ytResult').textContent=arr.map((x,i)=>`${i+1}. ${x}`).join('\n');}
function makeCaption(){const t=$('captionTopic').value.trim(),m=$('captionMood').value;if(!t)return $('captionResult').textContent='Enter a post topic first.';const bank={Cool:`${t} — simple moments, solid vibes. ✨ #GoodVibes`,Funny:`POV: ${t} was supposed to be easy 😂 #Relatable`,Motivational:`Small steps, big change. Today’s focus: ${t}. 💪 #Motivation`,Simple:`${t}. That’s the post. 🙂`};$('captionResult').textContent=bank[m];}
$('toolSearch')?.addEventListener('input',filterTools);
document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');filterTools();}));
function filterTools(){const q=$('toolSearch').value.toLowerCase().trim(),f=document.querySelector('.chip.active').dataset.filter;document.querySelectorAll('.tool-card').forEach(card=>{const okCat=f==='all'||card.dataset.category===f,okQ=!q||(card.dataset.name+' '+card.textContent.toLowerCase()).includes(q);card.classList.toggle('hidden',!(okCat&&okQ));});}
let lang='en';
$('langToggle')?.addEventListener('click',()=>{lang=lang==='en'?'hi':'en';$('langToggle').textContent=lang==='en'?'हिंदी':'English';document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{if(!el.dataset.en)el.dataset.en=el.textContent;const hi={eyebrow:'फ्री • तेज़ • मोबाइल फ्रेंडली',heroTitle:'हर दिन के काम के लिए स्मार्ट टूल्स।',heroCopy:'कैलकुलेटर, इमेज टूल्स, टेक्स्ट टूल्स और स्मार्ट कंटेंट जनरेटर — एक आसान Hindi + English वेबसाइट पर।'};el.textContent=lang==='hi'?(hi[el.dataset.i18n]||el.dataset.en):el.dataset.en;});});
$('year').textContent=new Date().getFullYear();
